### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Swayamsvk** [coding-blocks/boss#253]
While doing npm install I am getting this error:-

> semantic-ui@2.4.2 install /media/swayam/A:/BOSS/boss_back/boss/node_modules/semantic-ui
> gulp install

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'gulp-util'
Require stack:
- /usr/lib/nodejs/gulp/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/nodejs/gulp/bin/gulp.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/lib/nodejs/gulp/bin/gulp.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/swayam/.npm/_logs/2020-05-17T14_20_44_627Z-debug.log

Also tried version 8 and 10 still the error persists.

**Comment by abhishek97** [comment]
Look like you haven't install project dependecies.
try `npm install` or `yarn install`

**Comment by Swayamsvk** [comment]
Actually this error raises after I do npm install or yarn install.
